apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    app: db